#!/bin/sh

usage() {
    echo "Usage: $0 <os-platform>"
    exit 1
}

arch=$1

check_ct() {
	if [ "$arch" = "linux-x64" -o "$arch" = "linux" ]; then
		if  hash gcc 2>/dev/null; then
    		echo 'compiler: gcc ' `gcc -dumpversion`
		else
			echo 'Not found gcc compile, exit.'
	    	exit 1
		fi
	elif [ "$arch" = "openwrt" ]; then
		if  hash mipsel-openwrt-linux-gcc 2>/dev/null; then
    		echo 'compiler: mipsel-openwrt-linux-gcc ' `mipsel-openwrt-linux-gcc -dumpversion`
		else
			echo 'Not found mipsel-openwrt-linux-gcc compile, exit.'
	    	exit 1
		fi
	elif [ "$arch" = "rpi" ]; then
		if  hash arm-linux-gnueabihf-gcc 2>/dev/null; then
    		echo 'compiler: arm-linux-gnueabihf-gcc ' `arm-linux-gnueabihf-gcc -dumpversion`
		else
			echo 'Not found arm-linux-gnueabihf-gcc compile, exit.'
	    	exit 1
		fi
	elif [ "$arch" = "neo" ]; then
		if  hash arm-none-linux-gnueabihf-gcc 2>/dev/null; then
    		echo 'compiler: arm-none-linux-gnueabihf-gcc ' `arm-none-linux-gnueabihf-gcc -dumpversion`
		else
			echo 'Not found arm-none-linux-gnueabihf-gcc compile, exit.'
	    	exit 1
		fi
	else
		exit 1
	fi
}

if [ $# -ne 1 ]; then
    usage $*
fi

echo 'os target:' `uname -sri`
check_ct

PRO_DIR=$(pwd)
if [ ! -d  $PRO_DIR/objs ]; then
    mkdir $PRO_DIR/objs
fi

if [ ! -d  $PRO_DIR/live555 ]; then
    wget http://www.live555.com/liveMedia/public/live555-latest.tar.gz
    tar zxvf live555-latest.tar.gz && mv live live555 && rm -rf live555-latest.tar.gz
    cp config.rpi ./live555/config.armlinux-gnueabihf
    cp config.openwrt ./live555/config.mipsel-openwrt-linux
    cp config.neo ./live555/config.nanopi-neo
    patch -p0 < patches/live555.patch
fi

if [ ! -d  $PRO_DIR/srs-librtmp ]; then
    git clone https://github.com/aesirteam/srs-librtmp.git
fi

cd live555/liveMedia
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../groupsock
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../UsageEnvironment
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../BasicUsageEnvironment
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd $PRO_DIR/srs-librtmp
rm -f Makefile
cat Makefile.tail > Makefile

cd objs
rm -f Makefile
cat $PRO_DIR/config.$1 Makefile.tail > Makefile

cd $PRO_DIR
rm -f Makefile
cat Makefile.head config.$1 Makefile.tail > Makefile

cd src
rm -f Makefile
cat $PRO_DIR/config.$1 Makefile.tail > Makefile
